Repository TiiaSelin/Peliprojekti, pull requests merged in 2025-02, with the labels that each got.

#8 Pause menu fix
  scenes/game.tscn
  scenes/paused_menu.tscn
  scripts/game.gd
  scripts/paused_menu.gd
Labels: Fix

#10 Level control flow
  assets/images/portal.png
  assets/images/portal.png.import
  scenes/level_1.tscn
  scenes/level_2.tscn
  scenes/portal.tscn
  scripts/game.gd
  scripts/menu.gd
  scripts/portal.gd
Labels: feature

#11 Mob spawning
  scenes/level_1.tscn
  scenes/level_2.tscn
  scripts/game.gd
Labels: feature

#12 Sprite config
  assets/images/bee_spritesheet.png
  assets/images/bee_spritesheet.png.import
  assets/images/player_spritesheet.png
  assets/images/player_spritesheet.png.import
  scenes/bee.tscn
  scenes/level_1.tscn
  scenes/mob.tscn
  scenes/player.tscn
  scenes/portal.tscn
  scripts/bee.gd
  scripts/game.gd
  scripts/player.gd
Labels: feature

#13 Audio
  audio/Portal.wav
  audio/Portal.wav.import
  scenes/level_2.tscn
  scenes/menu.tscn
  scenes/paused_menu.tscn
  scenes/player.tscn
  scripts/game.gd
  scripts/gun.gd
  scripts/menu.gd
  scripts/paused_menu.gd
  scripts/player.gd
  scripts/portal.gd
  scripts/projectile.gd
Labels: feature

#15 Final level
  scenes/level_4.tscn
  scripts/final_level.gd
  scripts/paused_menu.gd
Labels: feature

#16 Audiolisäyksiä
  audio/pauseSound.wav
  audio/pauseSound.wav.import
  audio/resumeSound.wav
  audio/resumeSound.wav.import
  scenes/paused_menu.tscn
  scenes/player.tscn
  scripts/paused_menu.gd
  scripts/player.gd
Labels: enhancement, feature

#17 Boss stuff
  assets/images/big_bee_spritesheet.png
  assets/images/big_bee_spritesheet.png.import
  scenes/bee.tscn
  scenes/big_bee.tscn
  scenes/level_1.tscn
  scenes/level_2.tscn
  scenes/level_3.tscn
  scripts/big_bee.gd
  scripts/final_level.gd
  scripts/player.gd
Labels: feature

#18 Pienet muutokset
  scenes/level_1.tscn
  scenes/level_2.tscn
  scenes/level_3.tscn
  scenes/menu.tscn
  scenes/paused_menu.tscn
Labels: enhancement

#19 Removed unnecessary files and added new files.
  assets/images/bomb.png
  assets/images/bomb.png.import
  assets/images/mushroom.png
  assets/images/mushroom.png.import
  assets/images/projectile.png
  assets/images/projectile.webp
  assets/images/projectile.webp.import
  assets/images/revolver.png
  assets/images/staff.webp
  assets/images/staff.webp.import
  scenes/bee.tscn
  scenes/gun.tscn
  scenes/projectile.tscn
Labels: enhancement

#21 Portal animation
  assets/images/portal.png
  assets/images/portal_spritesheet.png
  assets/images/portal_spritesheet.png.import
  scenes/level_1.tscn
  scenes/level_2.tscn
  scenes/level_3.tscn
  scenes/portal.tscn
  scripts/game.gd
Labels: enhancement
